import { ICategory, IDish } from "./types";

export const dishes: IDish[] = [
  {
    id: 1,
    name: "Пицца Ассорти",
    price: 380,
    description: "Сочная пицца с тонким слоем сыра",
    category: [0, 3],
    cookingTime: "15-30 мин",
    imgUrl: "/images/pizza/pizza.jpg",
  },
  {
    id: 2,
    name: "Сладкие Панкейки",
    price: 200,
    description: "Вкуснейшие панкейки с медом и ягодами",
    category: [0, 1, 7],
    cookingTime: "10-15 мин",
    imgUrl: "/images/desert/pancakes.jpg",
  },
  {
    id: 3,
    name: "Салат Греческий",
    price: 240,
    description: "Свежий салат из полезных продуктов",
    category: [0, 4],
    cookingTime: "10-20 мин",
    imgUrl: "/images/salad/salad.jpg",
  },
  {
    id: 4,
    name: "Сочный Стейк",
    price: 990,
    description: "Стейк средней прожарки с гарниром",
    category: [0, 5],
    cookingTime: "20-35 мин",
    imgUrl: "/images/steak/steak.jpg",
  },
  {
    id: 5,
    name: "Аппетитный Стейк",
    price: 1290,
    description: "Стейк средней прожарки с гарниром",
    category: [0, 5],
    cookingTime: "20-35 мин",
    imgUrl: "/images/steak/steak-2.jpg",
  },
  {
    id: 6,
    name: "Превосходный Стейк",
    price: 1450,
    description: "Стейк средней прожарки с гарниром",
    category: [0, 5],
    cookingTime: "20-35 мин",
    imgUrl: "/images/steak/steak-3.jpg",
  },
  {
    id: 7,
    name: "Удивительный Стейк",
    price: 1100,
    description: "Стейк средней прожарки с гарниром",
    category: [0, 5],
    cookingTime: "20-35 мин",
    imgUrl: "/images/steak/steak-4.jpg",
  },
  {
    id: 8,
    name: "Прекрасный Стейк",
    price: 1090,
    description: "Стейк средней прожарки с гарниром",
    category: [0, 5],
    cookingTime: "20-35 мин",
    imgUrl: "/images/steak/steak-5.jpg",
  },
  {
    id: 9,
    name: "Круассан-бутерброд",
    price: 180,
    description: "Вкуснейший круассан",
    category: [0, 1],
    cookingTime: "10 мин",
    imgUrl: "/images/breakfast/breakfast.jpg",
  },
  {
    id: 10,
    name: "Яичница с авокадо",
    price: 210,
    description: "Классическая яичница с овощами",
    category: [0, 1],
    cookingTime: "5-10 мин",
    imgUrl: "/images/breakfast/breakfast-2.jpg",
  },
  {
    id: 11,
    name: "Бутерброд с огурцом и сметаной",
    price: 140,
    description: "Бутерброд с огурцом и сметаной",
    category: [0, 1],
    cookingTime: "5-10 мин",
    imgUrl: "/images/breakfast/breakfast-3.jpg",
  },
  {
    id: 12,
    name: "Бутерброд с семгой",
    price: 210,
    description: "Бутерброд с семгой",
    category: [0, 1],
    cookingTime: "5-10 мин",
    imgUrl: "/images/breakfast/breakfast-4.jpg",
  },
  {
    id: 13,
    name: "Блины с семгой",
    price: 210,
    description: "Блины с семгой",
    category: [0, 1],
    cookingTime: "5-10 мин",
    imgUrl: "/images/breakfast/breakfast-5.jpg",
  },
  {
    id: 14,
    name: "Шоколадный тортик",
    price: 190,
    description: "Шоколадный тортик",
    category: [0, 7],
    cookingTime: "5 мин",
    imgUrl: "/images/desert/desert.jpg",
  },
  {
    id: 15,
    name: "Тортик с клубникой",
    price: 210,
    description: "Тортик с клубникой",
    category: [0, 7],
    cookingTime: "5 мин",
    imgUrl: "/images/desert/desert-2.jpg",
  },
  {
    id: 16,
    name: "Наполеон",
    price: 150,
    description: "Классическая наполеон",
    category: [0, 7],
    cookingTime: "10 мин",
    imgUrl: "/images/desert/desert-3.jpg",
  },
  {
    id: 17,
    name: "Тирамису",
    price: 560,
    description: "Тирамису тортик",
    category: [0, 7],
    cookingTime: "10 мин",
    imgUrl: "/images/desert/desert-4.jpg",
  },
  {
    id: 18,
    name: "Трайфл",
    price: 150,
    description: "Трайфл со сгущенкой",
    category: [0, 7],
    cookingTime: "10 мин",
    imgUrl: "/images/desert/desert-5.jpg",
  },
  {
    id: 19,
    name: "Голубая логуна",
    price: 150,
    description: "Напиток голубая логуна",
    category: [0, 6],
    cookingTime: "5 мин",
    imgUrl: "/images/drink/drink.jpg",
  },
  {
    id: 20,
    name: "Красный дракон",
    price: 190,
    description: "Напиток красный дракон",
    category: [0, 6],
    cookingTime: "5 мин",
    imgUrl: "/images/drink/drink-2.jpg",
  },
  {
    id: 21,
    name: "Клубничный лимонад",
    price: 150,
    description: "Клубничный лимонад",
    category: [0, 6],
    cookingTime: "5 мин",
    imgUrl: "/images/drink/drink-3.jpg",
  },
  {
    id: 22,
    name: "Лимонад с малиной и еживикой",
    price: 110,
    description: "Лимонад с малиной и еживикой",
    category: [0, 6],
    cookingTime: "5 мин",
    imgUrl: "/images/drink/drink-4.jpg",
  },
  {
    id: 23,
    name: "Напиток ассорти",
    price: 210,
    description: "Напиток ассорти",
    category: [0, 6],
    cookingTime: "5 мин",
    imgUrl: "/images/drink/drink-5.jpg",
  },
  {
    id: 24,
    name: "Пиде",
    price: 150,
    description: "Пиде с яйцом, классическое",
    category: [0, 2],
    cookingTime: "10 мин",
    imgUrl: "/images/flour/pide.jpg",
  },
  {
    id: 25,
    name: "Чуду",
    price: 170,
    description: "Чуду с творогом",
    category: [0, 2],
    cookingTime: "10 мин",
    imgUrl: "/images/flour/chudu.jpg",
  },
  {
    id: 26,
    name: "Чуду с мясом",
    price: 210,
    description: "Чуду с мясом",
    category: [0, 2],
    cookingTime: "10 мин",
    imgUrl: "/images/flour/chudu-2.jpg",
  },
  {
    id: 27,
    name: "Мороженное со сгущенкой",
    price: 170,
    description: "Мороженное",
    category: [0, 8],
    cookingTime: "5 мин",
    imgUrl: "/images/icecream/icecream.jpg",
  },
  {
    id: 28,
    name: "Мороженное клубничное",
    price: 270,
    description: "Мороженное",
    category: [0, 8],
    cookingTime: "5 мин",
    imgUrl: "/images/icecream/icecream-2.jpg",
  },
  {
    id: 29,
    name: "Чистый пломбир",
    price: 230,
    description: "Пломбир",
    category: [0, 8],
    cookingTime: "5 мин",
    imgUrl: "/images/icecream/icecream-3.jpg",
  },
  {
    id: 30,
    name: "Ванильное мороженное",
    price: 160,
    description: "Мороженное",
    category: [0, 8],
    cookingTime: "5 мин",
    imgUrl: "/images/icecream/icecream-4.jpg",
  },
  {
    id: 31,
    name: "Голубое мороженное",
    price: 400,
    description: "Мороженное",
    category: [0, 8],
    cookingTime: "5 мин",
    imgUrl: "/images/icecream/icecream-5.jpg",
  },
  {
    id: 32,
    name: "Большое разноцветное мороженное",
    price: 170,
    description: "Мороженное",
    category: [0, 8],
    cookingTime: "5 мин",
    imgUrl: "/images/icecream/icecream-6.jpg",
  },
  {
    id: 33,
    name: "Пицца с оливковым маслом",
    price: 390,
    description: "Пицца",
    category: [0, 3],
    cookingTime: "20-25 мин",
    imgUrl: "/images/pizza/pizza-2.jpg",
  },
  {
    id: 34,
    name: "Пицца пепперони",
    price: 300,
    description: "Пицца",
    category: [0, 3],
    cookingTime: "20-25 мин",
    imgUrl: "/images/pizza/pizza-3.jpg",
  },
  {
    id: 35,
    name: "Пицца сырная",
    price: 370,
    description: "Пицца",
    category: [0, 3],
    cookingTime: "20-25 мин",
    imgUrl: "/images/pizza/pizza-4.jpg",
  },
  {
    id: 36,
    name: "Пицца маргарита",
    price: 390,
    description: "Пицца",
    category: [0, 3],
    cookingTime: "20-25 мин",
    imgUrl: "/images/pizza/pizza-5.jpg",
  },
  {
    id: 37,
    name: "Пицца овощная",
    price: 390,
    description: "Пицца",
    category: [0, 3],
    cookingTime: "20-25 мин",
    imgUrl: "/images/pizza/pizza-6.jpg",
  },
  {
    id: 38,
    name: "Пицца с помидорами",
    price: 390,
    description: "Пицца",
    category: [0, 3],
    cookingTime: "20-25 мин",
    imgUrl: "/images/pizza/pizza-7.jpg",
  },
  {
    id: 39,
    name: "Огурцовый салат с горошеком",
    price: 290,
    description: "Салат",
    category: [0, 4],
    cookingTime: "10-15 мин",
    imgUrl: "/images/salad/salad-2.jpg",
  },
  {
    id: 40,
    name: "Универсальный салат",
    price: 300,
    description: "Салат",
    category: [0, 4],
    cookingTime: "10-15 мин",
    imgUrl: "/images/salad/salad-3.jpg",
  },
  {
    id: 41,
    name: "Салат моряк",
    price: 290,
    description: "Салат",
    category: [0, 4],
    cookingTime: "10-15 мин",
    imgUrl: "/images/salad/salad-4.jpg",
  },
  {
    id: 42,
    name: "Салат оригинальный",
    price: 220,
    description: "Салат",
    category: [0, 4],
    cookingTime: "10-15 мин",
    imgUrl: "/images/salad/salad-5.jpg",
  },
  {
    id: 43,
    name: "Фркутовый салат",
    price: 390,
    description: "Салат",
    category: [0, 4],
    cookingTime: "10-15 мин",
    imgUrl: "/images/salad/salad-6.jpg",
  },
  {
    id: 44,
    name: "Салат полезный",
    price: 330,
    description: "Салат",
    category: [0, 4],
    cookingTime: "10-15 мин",
    imgUrl: "/images/salad/salad-7.jpg",
  },
];

export const categoryList: ICategory[] = [
  {
    id: 1,
    name: "Завтраки",
  },
  {
    id: 2,
    name: "Мучное",
  },
  {
    id: 3,
    name: "Пиццы",
  },
  {
    id: 4,
    name: "Салаты",
  },
  {
    id: 5,
    name: "Стейки",
  },
  {
    id: 6,
    name: "Напитки",
  },
  {
    id: 7,
    name: "Десерты",
  },
  {
    id: 8,
    name: "Мороженное",
  },
];
